kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config # object name
data: # key value data set
  nginx.conf : | #write nginx config configuration into configmap, the classic PHP FPM proxy setting, I won't talk about it here
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/slim_app;
        index index.php;
        server_name _;
        location / {
          try_files $uri $uri/ =404;
        }
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }